name: Docker

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'requirements.txt'
      - '.github/workflows/docker.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'requirements.txt'
      - '.github/workflows/docker.yml'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Check Docker build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

